command: ['python', 'app.py']
env:
  - name: 'CATALOG'
    value: 'bldemos'
  - name: 'SCHEMA'
    value: 'eo_analytics'
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: 'sql-warehouse'
  - name: 'GENIE_SPACE_ID'
    value: '01f17125e8741df2b08f8188fb0877b2'
  - name: 'NODE_ENV'
    value: 'production'
  - name: 'LAKEBASE_INSTANCE_NAME'
    value: 'dbrks-eo-lb'
  - name: 'DB_CONNECTION_STRING'
    valueFrom: 'lakebase-db'
  - name: 'MAILGUN_API_URL'
    value: 'https://api.mailgun.net/v3/datakafe.com/messages'
  - name: 'SENDER'
    value: 'robert@datakafe.com'
  - name: 'RECIPIENT'
    value: 'robert.leach@databricks.com'
